from enum import Enum


class Phase(str, Enum):
    SETUP = "SETUP"
    PRESEASON_READY = "PRESEASON_READY"
    REGULAR_SEASON_ACTIVE = "REGULAR_SEASON_ACTIVE"
    TRADE_DEADLINE_OPEN = "TRADE_DEADLINE_OPEN"
    REGULAR_SEASON_POSTDEADLINE = "REGULAR_SEASON_POSTDEADLINE"
    REGULAR_SEASON_COMPLETE = "REGULAR_SEASON_COMPLETE"
    PLAYIN_ACTIVE = "PLAYIN_ACTIVE"
    PLAYOFFS_R1 = "PLAYOFFS_R1"
    PLAYOFFS_R2 = "PLAYOFFS_R2"
    CONFERENCE_FINALS = "CONFERENCE_FINALS"
    NBA_FINALS = "NBA_FINALS"
    OFFSEASON_AWARDS_OPEN = "OFFSEASON_AWARDS_OPEN"
    OFFSEASON_AWARDS_CLOSED = "OFFSEASON_AWARDS_CLOSED"
    DRAFT_LOTTERY_DONE = "DRAFT_LOTTERY_DONE"
    DRAFT_IN_PROGRESS = "DRAFT_IN_PROGRESS"
    POST_DRAFT_TRADES_OPEN = "POST_DRAFT_TRADES_OPEN"
    FA_OPEN = "FA_OPEN"
    FA_CLOSED = "FA_CLOSED"
    WAIVERS_OPEN = "WAIVERS_OPEN"
    PROGRESSION_PENDING = "PROGRESSION_PENDING"
